config/routes.rb
Rails.application.routes.draw do
  get 'pages/account'

  get 'pages/finance'

  get 'pages/review'

  get 'pages/contract_agreement'

  resources :students, :courses
  root to: 'students#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :students, through: :starts
	has_many :start
end

app/models/start.rb
class Start < ApplicationRecord
  belongs_to :course
  has_many :students
end

app/models/student.rb
class Student < ApplicationRecord
	belongs_to :course
	belongs_to :start
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

	layout 'courses'

	def index
		@courses = Course.all
	end

	def show
		@course = Course.find(params[:id])
		@students = @course.students.all
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def account
  end

  def finance
  end

  def review
  end

  def contract_agreement
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  layout 'students'

  def index
    @students = Student.all
  end

  def show
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:f_name, 
                                      :l_name, 
                                      :phone, 
                                      :address_one, 
                                      :address_two, 
                                      :email, 
                                      :city, 
                                      :state, 
                                      :zip, 
                                      :dob, 
                                      :military_status, 
                                      :education, 
                                      :experience, 
                                      :employment_status, 
                                      :salary, 
                                      :gender,
                                      :format_type,
                                      :course_id,
                                      :start_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/index.html.erb
<h1>I'm the course index page</h1>

<table>
	<thead>
		<tr>
			<th>Course Name</th>
			<th>Start date</th>
		</tr>
	</thead>

<tbody>
	<% @courses.each do |course| %>
		<tr>
			<td><%= link_to course.name, course_path(course) %></td>
		</tr>
	<% end %>
</tbody>
	
</table>

app/views/courses/show.html.erb
<h1>I'm the Course show page</h1>

<%= @course.name %>

<% @students.each do |student| %>
	<%= student.f_name %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'contracts', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
    <div id="app">
        <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/layouts/courses.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bottega</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'courses', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div id="app-wrapper">
    	<%= yield %>
  	</div>
  </body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bottega || Account</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'pages', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="app-wrapper">
  		<%= render 'shared/header' %>
    	<%= yield %>
    </div>
  </body>
</html>

app/views/layouts/sldfjlsjd7contracts.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRails</title>

  </head>

  <body>
    <%= yield %>
    <div id="app">
  </body>
</html>

app/views/layouts/students.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bottega</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'students', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div id="app-wrapper">
  		<%= render 'shared/header' %>
    	<%= yield %>
  	</div>
  </body>
</html>

app/views/pages/account.html.erb
<h1>Pages#account</h1>
<p>Find me in app/views/pages/account.html.erb</p>

app/views/pages/finance.html.erb
<h1>Pages#finance</h1>
<p>Find me in app/views/pages/finance.html.erb</p>

app/views/pages/review.html.erb
<h1>Pages#review</h1>
<p>Find me in app/views/pages/review.html.erb</p>

app/views/shared/_header.html.erb
<div id="header"><%= image_tag "bottega-white-logo.png", width: 92, height: 14 %></div>

<div id="nav-bar">
	<div class="for-navbar">
		<span class="nav-item">
			<div class="status-icons <%= 'active-icon' if current_page?(root_path) %><%= 'active-icon' if current_page?(new_student_path) %>">
				<p>1</p>
			</div>
				<p class="nav-info <%= 'active-text' if current_page?(root_path) %><%= 'active-text' if current_page?(new_student_path) %>">Application<br/>Form</p>
		</span>

		<span class="nav-item">
			<div class="status-icons <%= 'active-icon' if current_page?(@student) %>">
				<p>2</p>
			</div>
				<p class="nav-info <%= 'active-text' if current_page?(@student) %>">Contract<br/>Agreement</p>
		</span>

		<span class="nav-item">
			<div class="status-icons <%= 'active-icon' if current_page?(pages_account_path) %>">
				<p>3</p>
			</div>
				<p class="nav-info <%= 'active-text' if current_page?(pages_account_path) %>">Account<br/>Set-Up</p>
		</span>

		<span class="nav-item">
			<div class="status-icons <%= 'active-icon' if current_page?(pages_finance_path) %>">
				<p>4</p>
			</div>
				<p class="nav-info <%= 'active-text' if current_page?(pages_finance_path) %>">Financial<br/>Guidance</p>
		</span>

		<span class="nav-item">
			<div class="status-icons <%= 'active-icon' if current_page?(pages_review_path) %>">
				<p>5</p>
			</div>
				<p class="nav-info <%= 'active-text' if current_page?(pages_review_path) %>">Review</p>
		</span>
	</div>
</div>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |f| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'form_modal', f: f %>

  <%= render 'main_fields', f: f %>
<% end %>

<script>
  let modal = document.getElementById('course-modal');
  let btn = document.getElementsByClassName('trigger')[0];
  let closeButton = document.getElementsByClassName("close-n-save")[0];

  btn.onclick = function() {
    modal.style.display = "block";
  }

  closeButton.onclick = function() {
    modal.style.display = "none";
  }

  window.onclick = function(event) {
    if (event.target == modal) {
      modal.style.display = "none";
    }
  }



</script>

app/views/students/_form_modal.html.erb
<div id="course-card">
  <div class="change-course">
    <span class="float-right">Not Correct? <span class="trigger">Change</span></span>
  </div>
  <div class="course-icon"></div>
  <div class="course-text">
    <h2>Full Stack<br />Python + JavaScript</h2>
    <p>Full-Time, On-Campus</p>
    <span>Powered by Bottega</span>
  </div>
  <div class="course-info">
    <div class="form-row">
      <div class="col-md-6">
        <p>Course Duration</p>
        <span>12 Weeks</span>
      </div>
      <div class="col-md-6">
        <p>Start Date</p>
        <span>August 28, 2018</span>
      </div>
    </div>
  </div>
</div>

<div id="course-modal" class="a-cool-modal">
  <div class="for-modal">
    <div class="modal-card">
      <h1>Track Selection_</h1>
      <div class="content-for-modal">
        <div class="track-icon-box">
          <div class="form-row">
            <div class="col-md-3">
              <div class="track-icon">
                <%= image_tag 'frontend.svg', width: 43, height: 60 %>
                <p>Some placeholder text yeeeeeeeeeeeeeeee!</p>
              </div>
            </div>
            <div class="col-md-3">
              <div class="track-icon">
                <%= image_tag 'frontend.svg', width: 43, height: 60 %>
                <p>Some placeholder text yeeeeeeeeeeeeeeee!</p>
              </div>
            </div>
            <div class="col-md-3">
              <div class="track-icon">
                <%= image_tag 'frontend.svg', width: 43, height: 60 %>
                <p>Some placeholder text yeeeeeeeeeeeeeeee!</p>
              </div>
            </div>
            <div class="col-md-3">
              <div class="track-icon">
                <%= image_tag 'data_science.svg', width: 43, height: 60 %>
                <p>Some placeholder text yeeeeeeeeeeeeeeee!</p>
              </div>
            </div>
          </div>
        </div>
        <div class="class-select-fields">
          <p>Program Format</p>
          <%= f.select(:format_type, options_for_select([
                                                        ["Part-Time", "Part-Time"],
                                                        ["Full-Time", "Full-Time"]]), 
                                                        { include_blank: true }) %>
          <p>Start Date</p>
          <%= f.collection_select(:start_id, Start.all, :id, :start_date, { include_blank: true }) %>
        </div>
      </div>
    </div>
    <div class="modal-btn-box">
      <span class="close-n-save">Close & Save</span>
    </div>
  </div>
</div>

app/views/students/_main_fields.html.erb
<div id="new-form-card">
  <div class="form-header"><p>Applicant Information_</p></div>
  <div class="new-student-form-fields">
    <div id="contact-info">
      <div class="form-row">
        <div class="col-md-6 mb-4">
          <p>First Name</p>
          <%= f.text_field :f_name, id: :student_f_name %>
        </div>

        <div class="col-md-6 mb-4">
          <p>Last Name</p>
          <%= f.text_field :l_name, id: :student_l_name %>
        </div>
      </div>

      <div class="mb-4">
        <p>Email</p>
        <%= f.text_field :email, id: :student_email %>
      </div>

      <div class="mb-4">
        <p>Phone #</p>
        <%= f.text_field :phone, id: :student_phone %>
      </div>
    </div>

    <div id="location">
      <div class="mb-4">
        <p>Street Address One</p>
        <%= f.text_field :address_one, id: :student_address_one %>
      </div>

      <div class="mb-4">
        <p>Street Address Two</p>
        <%= f.text_field :address_two, id: :student_address_two, placeholder: 'Apartment #, Suite, etc.' %>
      </div>

      <div class="form-row">
        <div class="col-md-4 mb-4">
          <p>City</p>
          <%= f.text_field :city, id: :student_city %>
        </div>

        <div class="col-md-4 mb-4">
          <p>State</p>
          <%= f.text_field :state, id: :student_state %>
        </div>

        <div class="col-md-4 mb-4">
          <p>Zip Code</p>
          <%= f.text_field :zip, id: :student_zip %>
        </div>
      </div>
    </div>

    <div id="select-fields">
      <div id="date-field-box">
        <div class="date-fields">
          <p>Date of Birth</p>
            <%= f.date_select :dob, 
                                  id: :student_dob, 
                                  start_year: Date.today.year - 70, 
                                  end_year: Date.today.year - 17, 
                                  order: [:month, :day, :year],
                                  include_blank: true %>
        </div>
      </div>

      <div class="form-row mb-4">
        <div class="col-md-6">
          <p>Gender</p>
          <%= f.select(:gender, options_for_select([['Female', 'Female'],
                                                    ['Male', 'Male'],
                                                    ['I dont wish to share', 'N/A']]), { include_blank: true }) %>
        </div>

        <div class="col-md-6">
          <p>Military Service</p>
          <%= f.select(:military_status, options_for_select([['Active Duty', 'Active'],
                                                            ['Veteran', 'Veteran'],
                                                            ['Active Reserve', 'Active Reserve'],
                                                            ['Inactive Reserve', 'Inactive Reserve'],
                                                            ['I dont wish to share', 'N/A'],
                                                            ['Civilian', 'Civilian']]), { include_blank: true }) %>
        </div>
      </div>

      <div class="form-row mb-4">
        <div class="col-md-6">
          <p>Highest Education Level</p>
          <%= f.select(:education, options_for_select([['N/A', 'N/A'], 
                                                        ['Highschool or Equivilent', 'Highschool'], 
                                                        ['Some college', 'Some college'], 
                                                        ['Associates', 'Associates'], 
                                                        ['Bachelors', 'Bachelors']]), { include_blank: true }) %>
        </div>

        <div class="col-md-6">
          <p>Previous Coding Experience</p>
          <%= f.select(:experience, options_for_select([['None', 'None'], 
                                                        ['Tried it once or twice', 'Little'], 
                                                        ['Well versed in a language', 'Moderate'], 
                                                        ['Experience in the field', 'Experienced']]), { include_blank: true }) %>
        </div>
      </div>

      <div class="form-row mb-4">
        <div class="col-md-6">
          <p>Current Employment Status</p>
          <%= f.select(:employment_status, options_for_select([['Employed', 'Employed'], 
                                                              ['Unemployed', 'Unemployed']]), { include_blank: true }) %>
        </div>

        <div class="col-md-6">
          <p>Current Income</p>
          <%= f.select(:salary, options_for_select([['$15,000', '15k'],
                                                    ['$20,000', '20k'],
                                                    ['$25,000', '25k'],
                                                    ['$30,000', '30k'],
                                                    ['$35,000', '35k'],
                                                    ['$40,000', '40k'],
                                                    ['$45,000', '45k'],
                                                    ['$50,000 or higher', '> 50k']]), { include_blank: true }) %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="btn-box">
  <%= f.submit "Continue", class: 'save-student-btn' %>
</div>

app/views/students/edit.html.erb
<%= render 'form', student: @student %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>F name</th>
      <th>L name</th>
      <th>Phone</th>
      <th>Address one</th>
      <th>Address two</th>
      <th>Email</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Dob</th>
      <th>Course</th>
      <th>Military status</th>
      <th>Education</th>
      <th>Experience</th>
      <th>Employment status</th>
      <th>Salary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.f_name %></td>
        <td><%= student.l_name %></td>
        <td><%= student.phone %></td>
        <td><%= student.address_one %></td>
        <td><%= student.address_two %></td>
        <td><%= student.email %></td>
        <td><%= student.city %></td>
        <td><%= student.state %></td>
        <td><%= student.zip %></td>
        <td><%= student.dob %></td>
        <td><%= student.course %></td>
        <td><%= student.military_status %></td>
        <td><%= student.education %></td>
        <td><%= student.experience %></td>
        <td><%= student.employment_status %></td>
        <td><%= student.salary %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<%= render 'form', student: @student %>